# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Relationships', folder: 'pages', file: 'relationships.html'}
- {name: 'Travel', folder: 'pages', file: 'travel.html'}
- {name: 'Everyday', folder: 'pages', file: 'everyday.html'}
- {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://www.instagram.com/oh.weller/?hl=en'}
- {icon: 'facebook', link: 'https://www.facebook.com/wellerwellness/'}
- {icon: 'pinterest', link: 'https://www.pinterest.com/thehaileyweller/'}
- {icon: 'envelope', link: 'mailto:haileyaweller@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
